### PR TITLE
Use closure actions to trigger loading state when fetching results

### PR DESCRIPTION
**Pull request by thechrisnixon**
Could also make it so you can pass a string rather than just a closure action, just let me know. Thanks for the awesome library.

### CODE REVIEW

**Comment by Artistan** [comment]
implemented in fork/rename to hypersearch**er**...
https://www.npmjs.com/package/ember-hypersearcher

**Comment by thechrisnixon** [comment]
@poteto I rebased, is this still being maintained?

**Comment by poteto** [comment]
Yes, thanks for letting me know about the update! 

@homu r+

**Comment by thechrisnixon** [comment]
Thanks, whoa that @homu is cool. I need to check that out.

**Pull request merged**
