### PR TITLE
Fix *super small* typo in block form example

### PR DESCRIPTION
**Pull request by mattmcmanus**
I didn't even notice this until I copied the example into my editor and the syntax highlighting was all like "Wha!?"

I'm loving this addon. Thanks!

### CODE REVIEW

**Comment by poteto** [comment]
Hey thanks! I need to update ember cli before I can merge this (the jQuery issue is very annoying).

**Comment by Artistan** [comment]
implemented in fork/rename to hypersearch**er**...
https://www.npmjs.com/package/ember-hypersearcher

**Comment by poteto** [comment]
@Artistan please stop commenting on every issue and PR.

**Comment by Artistan** [comment]
I commented on them because I have integrated them all into a fork.
You were unresponsive to my original posts and needed to move forward.

**Comment by mattmcmanus** [comment]
Hey, @Artistan, I get it, I was working on my own fork as well. However, commenting on each PR about your fork feels like a hostile take over. There is no need for that. 

Yellow card

**Comment by Artistan** [comment]
no offense intended. 
There was 4 months of no updates and no response to my post on one of the PRs in a couple of weeks.
My intent was to inform the people who made the requests and/or find those issues.
I have nothing to gain from "taking over". Cheers!

**Pull request closed without merging**
